### ISSUE TITLE
Magento 2.2

### ISSUE THREAD

**Issue by inelukipg** [tobias-forkel/Magento2_CustomShipping#2]
Hi!

Do you know if this module works with Magento 2.2?

**Comment by tobias-forkel** [comment]
Hi @inelukipg 

Yes you should be fine to use it in 2.2.x. However, there was a problem in the composer.json file which I have fixed in 1.2.1.

![magento2_customshipping_ 2](https://user-images.githubusercontent.com/8432605/33295696-50252298-d42b-11e7-8bcf-2832d2fb566e.jpg)

If you are using composer, simply pull the latest release as follows:

`composer require "tobias-forkel/magento2-customshipping":"1.2.1"`

Let me know if there is anything else I can help with.

Cheers,
Tobias

**Comment by inelukipg** [comment]
Great! 
I'm using 2.1.8 right now but planning to upgrade to 2.2 later on.
